Repository PagerDuty/pd-live-react, pull requests merged in 2023-07, with the labels that each got.

#138 [Release] v0.8.3 beta.0
  .github/workflows/cd-workflow.yml
  .github/workflows/lint-workflow.yml
  .github/workflows/test-workflow.yml
  cypress.config.js
  cypress/e2e/Incidents/incidents.spec.js
  cypress/e2e/app.spec.js
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/support/util/common.js
  package.json
  src/components/IncidentTable/IncidentTableComponent.js
  src/components/NavigationBar/StatusBeaconComponent.js
  src/config/version.js
  src/redux/incident_actions/sagas.js
  src/util/pd-api-wrapper.js
  yarn.lock
Labels: release

#148 [Release] v0.8.4 beta.0
  package.json
  src/config/version.js
  src/util/pd-api-wrapper.js
  yarn.lock
Labels: release

#159 Add linkify URLs in notes
  cypress/e2e/Incidents/incidents.spec.js
  cypress/support/util/common.js
  package.json
  src/config/column-generator.js
  yarn.lock
Labels: enhancement

#158 Add a column for incident responders
  cypress/e2e/Incidents/incidents.spec.js
  src/components/IncidentTable/subcomponents/PersonInitialsComponents.js
  src/config/column-generator.js
  src/config/fuse-config.js
Labels: enhancement

#152 [Snyk] Upgrade web-vitals from 3.3.1 to 3.3.2
  package.json
  yarn.lock
Labels: dependencies, npm

#133 [Snyk] Upgrade typescript from 5.0.4 to 5.1.3
  package.json
  yarn.lock
Labels: dependencies

#135 [Snyk] Upgrade react-icons from 4.8.0 to 4.9.0
  package.json
  yarn.lock
Labels: dependencies

#168 actions for large numbers of incidents
  .tool-versions
  src/components/IncidentActions/subcomponents/SelectedIncidentsComponent.js
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/id/translation.json
  src/locales/ja/translation.json
  src/locales/pt-br/translation.json
  src/locales/pt/translation.json
  src/redux/incident_actions/sagas.js
  src/util/helpers.js
  src/util/incidents.js
  src/util/pd-api-wrapper.js
  src/util/sagas.js
Labels: fix

#180 show an error if the user attempts to get >10000 incidents
  src/components/IncidentTable/IncidentTableComponent.js
  src/components/IncidentTable/subcomponents/EmptyIncidentsComponent.js
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/id/translation.json
  src/locales/ja/translation.json
  src/locales/pt-br/translation.json
  src/locales/pt/translation.json
  src/redux/incidents/sagas.js
Labels: fix

#169 i18n updates
  i18next-parser.config.js
  package.json
  src/config/column-generator.js
  src/config/fuse-config.js
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/id/translation.json
  src/locales/ja/translation.json
  src/locales/pt-br/translation.json
  src/locales/pt/translation.json
  yarn.lock
Labels: task

#185 [Release] v0.9.0 beta.0
  .github/dependabot.yml
  .github/workflows/cd-workflow.yml
  .github/workflows/snyk-security.yml
  .github/workflows/test-workflow.yml
  .tool-versions
  README.md
  cypress/e2e/Incidents/incidents.spec.js
  cypress/e2e/Query/query.spec.js
  cypress/e2e/Settings/settings.spec.js
  cypress/support/util/common.js
  i18next-parser.config.js
  package.json
  src/components/IncidentActions/subcomponents/SelectedIncidentsComponent.js
  src/components/IncidentTable/IncidentTableComponent.js
  src/components/IncidentTable/subcomponents/EmptyIncidentsComponent.js
  src/components/IncidentTable/subcomponents/PersonInitialsComponents.js
  src/components/SettingsModal/SettingsModalComponent.js
  src/components/SettingsModal/SettingsModalComponent.test.js
  src/config/column-generator.js
  src/config/fuse-config.js
  src/config/version.js
  src/i18n.js
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/id/translation.json
  src/locales/ja/translation.json
  src/locales/pt-br/translation.json
  src/locales/pt/translation.json
  src/redux/incident_actions/sagas.js
  src/redux/incidents/sagas.js
  src/redux/query_settings/sagas.js
  src/redux/query_settings/sagas.test.js
  src/redux/rootSaga.js
  src/redux/settings/actions.js
  src/redux/settings/reducers.js
  src/redux/settings/sagas.js
  src/redux/settings/sagas.test.js
  src/util/helpers.js
  src/util/incidents.js
  src/util/pd-api-wrapper.js
  src/util/sagas.js
  yarn.lock
Labels: release
