Repository PagerDuty/pd-live-react, pull requests merged in 2023-08, with the labels that each got.

#210 Ensure PersonInitialsComponent still renders even if users map isn't loaded yet
  src/components/IncidentTable/subcomponents/PersonInitialsComponents.js
Labels: fix

#211 [Release] v0.9.1 beta.0
  .github/workflows/cd-workflow.yml
  .github/workflows/dependency-review.yml
  .github/workflows/lint-workflow.yml
  package.json
  src/components/IncidentTable/subcomponents/PersonInitialsComponents.js
  src/config/version.js
  yarn.lock
Labels: release

#228 [Release] v0.9.2 beta.0
  .github/workflows/cd-workflow.yml
  .github/workflows/lint-workflow.yml
  .github/workflows/test-workflow.yml
  .gitignore
  cypress/e2e/Incidents/incidents.spec.js
  cypress/e2e/Query/query.spec.js
  cypress/e2e/Settings/settings.spec.js
  cypress/e2e/app.spec.js
  package.json
  src/App.js
  src/components/ColumnsModal/ColumnsModalComponent.js
  src/components/ColumnsModal/ColumnsModalComponent.test.js
  src/components/IncidentActions/subcomponents/SelectedIncidentsComponent.js
  src/components/IncidentTable/IncidentTableComponent.js
  src/components/IncidentTable/subcomponents/PersonInitialsComponents.test.js
  src/components/NavigationBar/NavigationBarComponent.js
  src/components/NavigationBar/StatusBeaconComponent.js
  src/components/NavigationBar/subcomponents/LoadSavePresetsModal.js
  src/components/QuerySettings/QuerySettingsComponent.js
  src/components/QuerySettings/subcomponents/DatePickerComponent.js
  src/components/QuerySettings/subcomponents/DatePickerComponent.scss
  src/components/SettingsModal/SettingsModalComponent.js
  src/config/column-generator.js
  src/config/version.js
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/locales/es/translation.json
  src/locales/fr/translation.json
  src/locales/id/translation.json
  src/locales/ja/translation.json
  src/locales/pt-br/translation.json
  src/locales/pt/translation.json
  src/redux/escalation_policies/sagas.js
  src/redux/extensions/sagas.js
  src/redux/incident_actions/sagas.js
  src/redux/incidents/reducers.js
  src/redux/incidents/sagas.js
  src/redux/persistence/config.js
  src/redux/priorities/sagas.js
  src/redux/query_settings/actions.js
  src/redux/query_settings/reducers.js
  src/redux/query_settings/sagas.js
  src/redux/response_plays/sagas.js
  src/redux/rootSaga.js
  src/redux/services/sagas.js
  src/redux/settings/actions.js
  src/redux/settings/reducers.js
  src/redux/settings/sagas.js
  src/redux/settings/sagas.test.js
  src/redux/teams/sagas.js
  src/redux/users/sagas.js
  src/util/auth.test.js
  src/util/pd-api-wrapper.js
  src/util/sagas.js
  yarn.lock
Labels: release

#245 Fix "You passed a container to the second argument of root.render(...)" warning
  src/index.jsx
Labels: task

#251 Expand linting to all directories
  .eslintrc.js
  cypress.config.js
  cypress/e2e/Incidents/incidents.spec.js
  cypress/e2e/Query/query.spec.js
  cypress/e2e/Settings/settings.spec.js
  cypress/e2e/app.spec.js
  cypress/support/e2e.js
  cypress/support/util/common.js
  i18next-parser.config.js
  package.json
  src/redux/incidents/sagas.js
  vite.config.js
  yarn.lock
Labels: task

#145 Upgrade to Node 20.5.1 for development, testing and deployment
  .github/workflows/test-workflow.yml
  .tool-versions
  README.md
Labels: task

#284 Fix bug where custom columns restored from a presets file would be lost if rearranged
  src/components/ColumnsModal/ColumnsModalComponent.jsx
  src/components/NavigationBar/subcomponents/LoadSavePresetsModal.jsx
Labels: fix
